--- 
- 
  name: "Install Java 1.7 and some basic dependencies"
  with_items: 
    - unzip
    - java-1.7.0-openjdk
    - libselinux-python
    - libsemanage-python
  yum: "name={{item}} state=present"
- 
  get_url: "url=http://download.jboss.org/jbossas/7.1/jboss-as-7.1.1.Final/jboss-as-7.1.1.Final.zip dest=/opt/jboss-as-7.1.1.Final.zip"
  name: "Download JBoss from jboss.org"
- 
  name: "Extract archive"
  unarchive: "dest=/usr/share src=/opt/jboss-as-7.1.1.Final.zip creates=/usr/share/jboss-as copy=no"
- 
  command: "chdir=/usr/share /bin/mv jboss-as-7.1.1.Final jboss-as creates=/usr/share/jboss-as"
  name: "Rename install directory"
- 
  name: "Copying standalone.xml configuration file"
  notify: "restart jboss"
  template: "src=standalone.xml dest=/usr/share/jboss-as/standalone/configuration/"
- 
  group: name=jboss
  name: "Add group \"jboss\""
- 
  name: "Add user \"jboss\""
  user: "name=jboss group=jboss home=/usr/share/jboss-as"
- 
  get_url: 
    dest: /usr/share/jboss-as/
    url: "https://repo1.maven.org/maven2/org/jboss/modules/jboss-modules/1.1.5.GA/jboss-modules-1.1.5.GA.jar"
  name: "Download jboss-modules-1.1.5.GA.jar"
- 
  file: "path=/usr/share/jboss-as/ owner=jboss group=jboss state=directory recurse=yes"
  name: "Change ownership of JBoss installation"
- 
  copy: "src=jboss-redhat-standalone.sh dest=/etc/init.d/jboss mode=0755"
  name: "Copy the init script"
- 
  name: "Enable JBoss to be started at boot"
  service: "name=jboss enabled=yes state=started"

