---
- name: Install Java 1.8
  yum: name=java-1.{{java_version}}-openjdk-devel state=present

- name: add group "tomcat"
  group: name=tomcat

- name: add user "tomcat"
  user: name=tomcat group=tomcat home=/usr/share/tomcat createhome=no
  become: True
  become_method: sudo

- name: Download Tomcat
  get_url: url={{tomcat_tar_file}} dest=/opt/apache-tomcat-{{tomcat_version}}.tar.gz

- name: Extract archive
  command: chdir=/usr/share /bin/tar xvf /opt/apache-tomcat-{{tomcat_version}}.tar.gz -C /opt/ creates=/opt/apache-tomcat-{{tomcat_version}}

- name: Symlink install directory
  file: src=/opt/apache-tomcat-{{tomcat_version}} path=/usr/share/tomcat state=link

- name: Change ownership of Tomcat installation
  file: path=/usr/share/tomcat/ owner=tomcat group=tomcat state=directory recurse=yes

- name: Configure Tomcat server
  template: src=server.xml dest=/usr/share/tomcat/conf/
  notify: restart tomcat

- name: Configure Tomcat users
  template: src=tomcat-users.xml dest=/usr/share/tomcat/conf/
  notify: restart tomcat

- name: Install Tomcat init script
  template: 
    src: redhat-init.sh 
    dest: /etc/systemd/system/tomcat.service 
    mode: 0755

- name: Start Tomcat
  service: 
    name: tomcat
    state: started

- name: wait for tomcat to start
  wait_for: port={{http_port}}