---
# Installing software-properties-common for manage the repositories that you install
- name: Install add-apt-repostory
  apt: name=software-properties-common state=latest

# adding oracle java respository to apt respository
- name: Add Oracle Java Repository
  apt_repository: repo='ppa:openjdk-r/ppa'

# Installing Oracle java latest version from the local respository
- name: Install Oracle Java
  apt: name={{item}} state=latest
  with_items:
       - openjdk-8-jdk

- name: Installing Tomcat
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
          - tomcat9
          - tomcat9-docs
          - tomcat9-examples
          - tomcat9-admin

- name: Set java home path
  lineinfile:
    path: /etc/default/tomcat9
    line: 'JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64'

# copying configured server file to the tomcat configuration directory
- name: Configure Tomcat server
  template: src=server.xml dest=/var/lib/tomcat9/conf/
  notify: Restart tomcat
 
# copying configured tomcat-user file to tomcat configuration folder to manage web application 
- name: Configure Tomcat users
  template: src=tomcat-users.xml dest=/var/lib/tomcat9/conf/
  notify: Restart tomcat
 
# Making sure the tomcat server has started 
- name: Make sure the tomcat is started
  service:
    name: tomcat9
    state: started
