---
- name: Include centos.yml if the operating system is Amazon
  include: centos.yml
  when: ansible_distribution == "CentOS"

- name: Include redhat.yml if the operating system is redhat
  include: redhat.yml
  when: ansible_distribution == "RedHat"

- name: Include amazon.yml if the operating system is Ubuntu
  include: amazon.yml
  when: ansible_distribution == "Amazon"

- name: Include ubuntu.yml if the operating system is Ubuntu
  include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
