# tomcat port number
http_port: 8080
# https port number
https_port: 8443
# user for tomcat 
tomcat_user: tomcat
# group for tomcat
tomcat_group: tomcat
# login id for all the services in tomcat web server
manager_user: admin
# password for all the services in tomcat web server
manager_password: admin$ecret
# java version
java_version: "8.0"
# download link to tomcat web server tar ball
#tomcat_tar_file: http://archive.apache.org/dist/tomcat/tomcat-9/v9.0.35/bin/apache-tomcat-9.0.35.tar.gz
tomcat_tar_file: https://archive.apache.org/dist/tomcat/tomcat-9/v{{tomcat_version}}/bin/apache-tomcat-{{tomcat_version}}.tar.gz
# your server ip address to run automate test
tomcat_server_ip: "xx.xx.xx.xx"
