


#downloaded the tar file from the nodejs official website
- name: Download setup script
  get_url: url=https://rpm.nodesource.com/setup_{{node_version}} dest=/opt mode=755
- name: Setup Node.js
  command: /opt/setup_{{node_version}}
- name: Install Node.js (JavaScript run-time environment)
  package:
      name: nodejs
      state: present
- name: Install Git
  package:
      name: git
      state: present
- name: install angular cli
  raw: npm install -g @angular/cli
- name: Check the node version
  raw: node -v
  register: noderversionOut
- debug: 
    var: noderversionOut 
    verbosity: 2