

  - name: install wget
    yum: pkg='wget' state=installed

  - name: install jdk 7
    yum: pkg='java' state=installed
    sudo: true

  - name: create "nexus" group
    group: name=nexus 
    sudo: true

  - name: create "nexus" user
    user: name=nexus group=nexus 
    sudo: true

  - name: download the nexus from source file
    get_url: 
      url: https://download.sonatype.com/nexus/oss/nexus-{{ nexus_version }}-bundle.tar.gz
      dest: /opt/nexus-{{ nexus_version }}-bundle.tar.gz

 
  - name: untar the nexus file
    unarchive:
      src: /opt/nexus-{{ nexus_version }}-bundle.tar.gz
      dest: /usr/local/
      remote_src: True

  - name: make nexus directory property of "nexus" user/group
    file: path={{nexus_dir}} group=nexus owner=nexus recurse=true
    sudo: true
      
  - name: create symbolic links to /etc/init.d/nexus
    file: src={{nexus_dir}}/bin/nexus dest=/usr/local/nexus state=link
    sudo: true

  - name: changing the permissions for all nexus 
    shell: chmod 777 /usr/local/nexus-2.14.4-03

  - name: changing the permissions for all nexus 
    shell: chmod 777 /usr/local/sonatype-work/nexus  
  
  - name: configure nexus service
    template:
      src: nexus.service
      dest: /usr/lib/systemd/system
      
  - name: start the nexus service   
    service:
      name: nexus.service
      state: started

    

