

  - name: install wget
    yum: pkg='wget' state=present

  #Java Installation
  - name: Java Installation
    yum:
     name : java-1.8.0-openjdk-devel
     state : latest
    when: ansible_os_family == "RedHat"  or ansible_os_family == "CentOS"

  #Update
  - name: update apt-get
    apt:
     update_cache: yes
    when: ansible_os_family == "Debian"

  #Java installation when OS is ubuntu
  - name: Java Installation
    apt:
     name : default-jre
     state : latest
    when: ansible_os_family == "Debian"  

  - name: Java Installation JDK
    apt:
     name : openjdk-8-jdk
     state : latest
    when: ansible_os_family == "Debian"

  - name: create "nexus" group
    group: name=nexus 
    

  - name: create "nexus" user
    user: name=nexus group=nexus 
    

  - name: download the nexus from source file
    get_url: 
      url: https://download.sonatype.com/nexus/oss/nexus-{{ nexus_version }}-bundle.tar.gz
      dest: /opt/nexus-{{ nexus_version }}-bundle.tar.gz

 
  - name: untar the nexus file
    unarchive:
      src: /opt/nexus-{{ nexus_version }}-bundle.tar.gz
      dest: /usr/local/
      remote_src: True

  - name: make nexus directory property of "nexus" user/group
    file: path={{nexus_dir}} group=nexus owner=nexus recurse=true
    
      
  - name: create symbolic links to /etc/init.d/nexus
    file: src={{nexus_dir}}/bin/nexus dest=/usr/local/nexus state=link
    

  - name: changing the permissions for all nexus 
    shell: chmod 777 /usr/local/nexus-2.14.4-03

  - name: changing the permissions for all nexus 
    shell: chmod 777 /usr/local/sonatype-work/nexus  
  
  - name: configure nexus service
    template:
      src: nexus.service
      dest: /usr/lib/systemd/system
      
  - name: start the nexus service   
    service:
      name: nexus.service
      state: started

    

