---


# Checking OS family its ubntu do the taks otherwise skip it..
- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  

# Checking OS family its redhat do the taks otherwise skip it..
- include: redhat.yml
  when: ansible_distribution == 'RedHat' 
  
- name: Include amazon.yml if the operating system is amazon
  include: redhat.yml
  when: ansible_distribution == 'CentOS'

    
- name: Include redhat.yml if the operating system is centos
  include: ubuntu.yml
  when: ansible_distribution == 'Amazon'